# Generated by Django 4.2.7 on 2025-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_matching_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding (1536 dimensions)', null=True),
        ),
        migrations.AlterField(
            model_name='vacature',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding voor matching', null=True),
        ),
    ]
