# Generated by Django 4.2.7 on 2024-01-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vector_matching_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]
