# Generated by Django 4.2.7 on 2024-01-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_matching_app', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('embed_status', models.CharField(choices=[('queued', 'In wachtrij'), ('processing', 'Wordt verwerkt'), ('completed', 'Voltooid'), ('failed', 'Mislukt')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
