# Generated by Django 4.2.7 on 2024-01-01 00:03

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('vector_matching_app', '0003_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='house_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_titles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='extract_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='processing_step',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
