# Generated by Django 4.2.7 on 2025-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_matching_app', '0007_alter_prompt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('organisatie', models.CharField(max_length=255)),
                ('plaats', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
