# Generated by Django 4.2.7 on 2025-09-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_matching_app', '0009_cleanup_demo_vacatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacature',
            name='actief',
            field=models.BooleanField(default=True, help_text='Of de vacature nog actief is'),
        ),
        migrations.AddField(
            model_name='vacature',
            name='beschrijving',
            field=models.TextField(blank=True, help_text='Vacature beschrijving'),
        ),
        migrations.AddField(
            model_name='vacature',
            name='externe_id',
            field=models.CharField(default='temp', help_text='ID uit externe feed', max_length=100, unique=True),
        ),
    ]
