# Generated by Django 4.2.7 on 2025-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_matching_app', '0010_vacature_actief_vacature_beschrijving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacature',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding voor matching', null=True),
        ),
        migrations.AddField(
            model_name='vacature',
            name='samenvatting',
            field=models.TextField(blank=True, help_text='AI gegenereerde samenvatting'),
        ),
        migrations.AlterField(
            model_name='vacature',
            name='externe_id',
            field=models.CharField(help_text='ID uit externe feed', max_length=100, unique=True),
        ),
    ]
