# Generated by Django 4.2.7 on 2025-09-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vector_matching_app', '0011_vacature_embedding_vacature_samenvatting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Match score tussen 0 en 100 (1 decimaal)')),
                ('afstand_km', models.FloatField(blank=True, help_text='Afstand in kilometers', null=True)),
                ('afstand_berekend', models.BooleanField(default=False, help_text='Of de afstand is berekend')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kandidaat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='vector_matching_app.candidate')),
                ('vacature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='vector_matching_app.vacature')),
            ],
            options={
                'ordering': ['-score', '-timestamp'],
                'indexes': [models.Index(fields=['-score'], name='vector_matc_score_52d93b_idx'), models.Index(fields=['kandidaat', 'vacature'], name='vector_matc_kandida_7f9f54_idx')],
                'unique_together': {('kandidaat', 'vacature')},
            },
        ),
    ]
